parameters:
#    reflexe_media.example.class: Reflexe\Bundle\MediaBundle\Example

services:
#    reflexe_media.example:
#        class: %reflexe_media.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
